#!/usr/bin/env python3
"""What the vendor modules are, which are here, and which version each one is.

Reads  _workflow/config/modules.json          the declaration - what EXISTS
       <Module>/module.json            a module's own identity - what is HERE
       <Module>/_workflow/config/handoff/     the machine handoff snapshot, if any
       package.json                    THIS repository's version, written by semantic-release

This is a library. It has no main(), writes nothing, and prints nothing.

WHY IT EXISTS. A vendor module is a separate repository the user clones into this
repo's root, and the path is gitignored so the two git repos do not collide. That
buys a normal branch checkout inside each module and costs the one thing a git
submodule would have given for free: a recorded pin saying which vendor commit
belongs with which main-repo commit. modules.json is that pin, written out in a form
a human can read - and this module is the single place that reads it.

DECLARED IS NOT PRESENT. Keep the two apart. `declared_modules()` answers "what
control platforms does this machine have", which is a property of the project and is
the same in every checkout. `present_modules()` answers "what did this user clone",
which is their choice and varies. Generated documentation must be built from the
first, or a Siemens-only user's rebuild silently deletes every Beckhoff link from
tracked files. Reporting and version checks use the second.
"""

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "_workflow/config/modules.json"
SUPPORTED_SCHEMA = 1


class ModuleError(Exception):
    """A refusal. The caller prints it and writes nothing."""


# ------------------------------------------------------------------- the declaration


def _manifest(root=ROOT):
    """The parsed _workflow/config/modules.json, schema-checked."""
    path = root / "_workflow/config/modules.json"
    if not path.exists():
        raise ModuleError(
            f"{path.relative_to(root).as_posix()} is missing. It declares which vendor "
            f"modules this machine has; without it the generated pages would describe "
            f"whatever happens to be cloned, which is different for every user.")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise ModuleError(f"{path.name} is not valid JSON: {e}")
    if data.get("schema") != SUPPORTED_SCHEMA:
        raise ModuleError(
            f"{path.name} is schema {data.get('schema')}, this tool understands "
            f"{SUPPORTED_SCHEMA}. Refusing rather than guessing at fields that may have moved.")
    return data


def declared_modules(root=ROOT):
    """{name: info} from _workflow/config/modules.json, in declaration order.

    The authority on what exists. Independent of what is on disk, on purpose.
    """
    mods = _manifest(root).get("modules") or {}
    for name, info in mods.items():
        for key in ("url", "requires"):
            if not info.get(key):
                raise ModuleError(f"modules.json: module '{name}' has no '{key}'.")
    return mods


def module_dir(name, root=ROOT):
    return root / name


def is_present(name, root=ROOT):
    """On disk and not an empty directory.

    An empty directory is what a half-finished clone leaves behind, and it is worth
    telling apart from a module that was never cloned at all.
    """
    d = module_dir(name, root)
    return d.is_dir() and any(d.iterdir())


def present_modules(root=ROOT):
    """{name: info} for the declared modules this user actually has."""
    return {n: i for n, i in declared_modules(root).items() if is_present(n, root)}


def undeclared_dirs(root=ROOT):
    """Directories that look like a vendor module but are not declared.

    A module cloned under the wrong name, or one whose modules.json entry was never
    added. Neither builder will look at it, so saying so beats silence.
    """
    declared = set(declared_modules(root))
    out = []
    for d in sorted(root.iterdir()):
        if not d.is_dir() or d.name.startswith((".", "_")) or d.name in ("Unity",):
            continue
        if d.name in declared:
            continue
        if (d / "module.json").exists() or (d / "_docs/context").is_dir():
            out.append(d.name)
    return out


# ----------------------------------------------------------------------- the handoff

# Where a module keeps its committed copy of the main repo's .machine.json.
#
# NOT in the module's _docs/context/. That directory is generated BY the module and
# swept by its own builder, and three documents say never to hand-edit one. A committed
# INPUT that arrives from another repository does not belong in a generated output
# directory - the separate path is what keeps the two authorities apart.
HANDOFF_REL = "_workflow/config/handoff"


def handoff_dir(name, root=ROOT):
    return module_dir(name, root) / HANDOFF_REL


def wants_handoff(name, root=ROOT):
    """A module opts in by having the directory. Beckhoff does; Siemens does not yet."""
    return handoff_dir(name, root).is_dir()


def sha256_bytes(data):
    """A content hash that ignores line endings.

    NORMALISED, because the two things compared with it are copies of one generated
    file living in two different git repositories - and one of them may be read from a
    working tree, the other straight out of a blob over https. Without .gitattributes
    forcing eol=lf a Windows checkout stores CRLF and a Linux one LF, so a raw hash of
    the bytes answers differently depending on who ran the check, on a file whose
    content is identical. Normalising first makes the answer a property of the machine
    description rather than of the checkout.
    """
    import hashlib
    if data is None:
        return None
    return hashlib.sha256(data.replace(b"\r\n", b"\n")).hexdigest()


def sha256_of(path):
    try:
        return sha256_bytes(path.read_bytes())
    except OSError:
        return None


def handoff_state(name, root=ROOT):
    """{status, sha256, schema, exportCommit, syncedAtUtc, sourceRepo, upstreamUrl,
    upstreamRef} for a module's snapshot.

    status is one of: absent (module not cloned), opted-out (no handoff/ directory),
    missing (opted in, never synced), or ok.
    """
    out = {"status": "absent", "sha256": None, "schema": None,
           "exportCommit": None, "syncedAtUtc": None,
           # Where the snapshot came from. A module builds every link back to the
           # main repo out of these, so a change here is drift even when the
           # machine itself is byte-identical.
           "sourceRepo": None, "upstreamUrl": None, "upstreamRef": None}
    if not is_present(name, root):
        return out
    if not wants_handoff(name, root):
        out["status"] = "opted-out"
        return out
    d = handoff_dir(name, root)
    machine, meta = d / ".machine.json", d / ".handoff.json"
    if not machine.exists():
        out["status"] = "missing"
        return out
    out["status"] = "ok"
    out["sha256"] = sha256_of(machine)
    try:
        out["schema"] = json.loads(machine.read_text(encoding="utf-8")).get("schema")
    except (OSError, json.JSONDecodeError):
        out["status"] = "unreadable"
    if meta.exists():
        try:
            m = json.loads(meta.read_text(encoding="utf-8"))
            out["exportCommit"] = m.get("exportCommit")
            out["syncedAtUtc"] = m.get("syncedAtUtc")
            for k in ("sourceRepo", "upstreamUrl", "upstreamRef"):
                out[k] = m.get(k)
        except (OSError, json.JSONDecodeError):
            pass
    return out


def reference_machine(root=ROOT):
    """The main repo's own .machine.json: the thing every snapshot is compared against."""
    p = root / "_docs/context/.machine.json"
    if not p.exists():
        return None
    data = {}
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        pass
    return {"path": p, "sha256": sha256_of(p), "schema": data.get("schema"),
            "exportCommit": data.get("exportCommit"),
            "exportedAtUtc": data.get("exportedAtUtc"),
            # The per-scene stamps. The two top-level fields above are NOT a reliable
            # freshness signal on their own: re-exporting one scene updates that scene's
            # entry and leaves exportCommit and the top-level exportedAtUtc untouched, so
            # two builds that differ can carry an identical pair. Observed - a Siemens
            # re-export on 2026-08-26 shipped under exportCommit `5010e82 2026-08-23`.
            "scenes": {s.get("name"): s.get("exportedAtUtc")
                       for s in (data.get("scenes") or []) if isinstance(s, dict)}}


# ----------------------------------------------------------------------- the version


def _git(args, cwd, timeout=15):
    try:
        out = subprocess.run(["git", *args], cwd=cwd, capture_output=True,
                             text=True, timeout=timeout)
        return out.stdout.strip() if out.returncode == 0 else ""
    except Exception:
        return ""


def module_identity(name, root=ROOT):
    """{version, source, gitTag, mismatch, raw} for a module on disk.

    module.json first, `git describe` only as a cross-check. That order is what makes
    a ZIP download from GitHub behave exactly like a clone - it has no git metadata at
    all, and it is a completely reasonable way to take a copy of a PLC project.

    A disagreement between the two is reported, never fatal: it means someone tagged a
    release and did not bump module.json, or the reverse. Both are worth knowing and
    neither makes the module unusable.
    """
    d = module_dir(name, root)
    out = {"version": None, "source": None, "gitTag": None, "mismatch": None, "raw": {}}
    mj = d / "module.json"
    if mj.exists():
        try:
            raw = json.loads(mj.read_text(encoding="utf-8"))
            out["raw"] = raw
            if raw.get("version"):
                out["version"] = str(raw["version"])
                out["source"] = "module.json"
        except json.JSONDecodeError:
            out["mismatch"] = "module.json is not valid JSON"
            return out

    tag = _git(["describe", "--tags", "--abbrev=0"], cwd=d)
    if tag:
        out["gitTag"] = tag
        if out["version"] is None:
            out["version"] = tag.lstrip("vV")
            out["source"] = "git tag"
        elif _norm(tag) != _norm(out["version"]):
            out["mismatch"] = (f"module.json says {out['version']}, "
                               f"the newest git tag says {tag}")
    return out


def _norm(v):
    return str(v).strip().lstrip("vV")


# The version package.json carries before the first release has ever run. semantic-release
# never reads it - it works the next version out from the tags - so it is a placeholder, and
# reporting it as the main repo's version would say 0.0.0 to every `requiresMain` check.
PLACEHOLDER_VERSION = "0.0.0-semantic-release"


def main_version(root=ROOT):
    """{version, source, gitTag, mismatch} for THIS repository.

    Same shape and the same precedence as module_identity(), because the two answer the
    same question from opposite sides and a caller should not have to care which it is
    holding: the file first, `git describe` only as a cross-check, a disagreement
    reported and never fatal.

    package.json is the file. It is not a Node package - private, no dependencies, never
    published - it exists because semantic-release needs somewhere to write the version
    and because a module's `requiresMain` needs something to be checked against. Before
    the first release it still holds the placeholder, and then the newest tag is the
    better answer; version is None when there is neither, which is a real state on a
    fresh history and not an error.
    """
    out = {"version": None, "source": None, "gitTag": None, "mismatch": None}
    pkg = root / "package.json"
    if pkg.exists():
        try:
            raw = json.loads(pkg.read_text(encoding="utf-8"))
            v = str(raw.get("version") or "")
            if v and _norm(v) != _norm(PLACEHOLDER_VERSION):
                out["version"] = v
                out["source"] = "package.json"
        except json.JSONDecodeError as e:
            out["mismatch"] = f"package.json is not valid JSON: {e}"
            return out

    tag = _git(["describe", "--tags", "--abbrev=0"], cwd=root)
    if tag:
        out["gitTag"] = tag
        if out["version"] is None:
            out["version"] = _norm(tag)
            out["source"] = "git tag"
        elif _norm(tag) != _norm(out["version"]):
            out["mismatch"] = (f"package.json says {out['version']}, "
                               f"the newest git tag says {tag}")
    return out


def _parts(v):
    """A version as a comparable tuple. Non-numeric tails sort before a release."""
    core = re.split(r"[-+]", _norm(v), 1)
    nums = []
    for p in core[0].split("."):
        nums.append(int(p) if p.isdigit() else 0)
    while len(nums) < 3:
        nums.append(0)
    # 1.0.0-rc1 must sort BELOW 1.0.0, so a pre-release tail lowers the key.
    return (tuple(nums[:3]), 0 if len(core) > 1 else 1)


def satisfies(version, spec):
    """Does `version` satisfy `spec`? Returns True/False, or None if unknown.

    Deliberately small: >=, >, <=, <, ==, and a bare version meaning exact. Anything
    richer is a dependency solver, and a project with two modules does not need one.
    """
    if not version or not spec:
        return None
    for clause in [c.strip() for c in str(spec).split(",") if c.strip()]:
        m = re.match(r"^(>=|<=|==|>|<)?\s*(.+)$", clause)
        if not m:
            return None
        op, target = m.group(1) or "==", m.group(2)
        try:
            a, b = _parts(version), _parts(target)
        except (ValueError, AttributeError):
            return None
        ok = {">=": a >= b, "<=": a <= b, ">": a > b, "<": a < b, "==": a == b}[op]
        if not ok:
            return False
    return True


# -------------------------------------------------------------------- the main repo


def _normalise(url):
    """Strip any .git suffix and rewrite the scp-style form as https."""
    if not url:
        return ""
    url = re.sub(r"\.git$", "", url.strip())
    # git@github.com:Owner/Repo -> https://github.com/Owner/Repo
    m = re.match(r"^[\w.+-]+@([^:]+):(.+)$", url)
    if m:
        url = f"https://{m.group(1)}/{m.group(2)}"
    return url


def origin_url(root=ROOT):
    """The remote this checkout actually pushes to, or "" if there is none.

    A FACT about this working copy, not about the project. Use it only where a real
    git operation happens - publish_wiki.py pushing to <origin>.wiki.git. Never for a
    link in a generated page: a fork, a mirror or an SSH clone all give a different
    answer, and the page would then name whichever machine happened to build it.
    """
    return _normalise(_git(["remote", "get-url", "origin"], cwd=root))


def repo_url(root=ROOT):
    """The repository this project is PUBLISHED at - the URL a generated link names.

    DECLARED in modules.json, not probed from `git remote`, for the same reason vendor
    links are: a generated page is tracked, so its content must not depend on how the
    person who built it happened to clone. It also lets the published name change ahead
    of the remote actually being renamed, which is the only way a rename is ever a
    single edit.

    Falls back to origin when nothing is declared, so a fork with no manifest entry
    still produces working links rather than none.
    """
    try:
        declared = _normalise((_manifest(root).get("repository") or ""))
    except ModuleError:
        declared = ""
    return declared or origin_url(root)


def repo_name(root=ROOT):
    """The bare repository name, derived from origin rather than written down.

    The handoff a module commits records which repository it came from. Hardcoding
    that name means a rename on GitHub leaves every module asserting the old one, and
    nothing checks the claim - so derive it, and say nothing when there is no remote
    to derive it from.
    """
    url = repo_url(root)
    return url.rstrip("/").rsplit("/", 1)[-1] if url else ""


def src_ref(root=ROOT):
    """The branch a link into this repo should name.

    origin/HEAD, not the current branch: a generated link must point at the ref a
    reader will actually find the file on, and that is the repository's default
    branch, not whatever feature branch happened to build the page.
    """
    ref = _git(["symbolic-ref", "--short", "refs/remotes/origin/HEAD"], cwd=root)
    if ref.startswith("origin/"):
        return ref[len("origin/"):]
    return "master"


def module_ref(info):
    return info.get("branch") or "master"


def module_blob(info, rel):
    """An absolute URL to a path inside a vendor module's own repository.

    Absolute because there is no relative spelling that works. The module's directory
    is gitignored here, so it is absent both for most users and on GitHub entirely; a
    ../Beckhoff/... link is dead in every checkout that did not clone it. An absolute
    URL is true in all of them.
    """
    return f"{info['url'].rstrip('/')}/blob/{module_ref(info)}/{rel.lstrip('/')}"


def wiki_url(repo):
    """The GitHub wiki a repository publishes at.

    One wiki per repository, because a GitHub wiki IS a repository - <repo>.wiki.git -
    and a module is its own. The main repo's wiki carries the machine; a module's wiki
    carries that platform's realisation. Neither builds the other.
    """
    return f"{repo.rstrip('/')}/wiki" if repo else ""


class NotGitHub(Exception):
    """A URL we cannot derive a raw.githubusercontent.com address from."""


def raw_url(repo, ref, rel):
    """The raw-content URL for a file in a GitHub repository.

    WHY THIS EXISTS. A wiki page needs an image, and the image lives in the source
    repository. Copying the bytes into the wiki repo - which is what this replaced -
    gives every wiki its own duplicate of the figure set: a second copy that goes stale
    between publishes and is a second thing to keep true. Pointing at the source means
    the figure exists in exactly one place, and a re-rendered screenshot is live in the
    wiki the moment it is pushed, with no wiki build at all.

    Only github.com. A silently wrong image URL renders as a broken image and nothing
    says why, which is precisely the failure the wiki build exists to refuse on - so a
    host we cannot spell an address for is an error, not a guess.
    """
    m = re.match(r"^https?://(?:www\.)?github\.com/([^/]+)/([^/]+)/?$", (repo or "").strip())
    if not m:
        raise NotGitHub(
            f"cannot build a raw-content URL for '{repo}': only github.com repositories "
            f"have a raw.githubusercontent.com address this tool knows how to spell. "
            f"A guessed URL renders as a broken image with no explanation attached.")
    owner, name = m.group(1), m.group(2)
    return (f"https://raw.githubusercontent.com/{owner}/{name}/"
            f"{ref}/{rel.lstrip('/')}")


# --------------------------------------------------------------------------- fetching


def fetch_json(url, timeout=15):
    """{status, data, raw, detail} for a JSON file fetched over https.

    `raw` is the undecoded bytes, kept so a caller can hash the content it actually
    received rather than a re-serialisation of it.

    status is one of: ok, missing (a 404 - the file is genuinely not there), or
    unreachable (anything else: no network, a timeout, a rename, a private repository).

    THE TWO FAILURES ARE NOT THE SAME. A 404 on a module's handoff means that module is
    not a consumer of the machine description, which is a fact worth reporting. Having
    no network means nothing was learned at all. Collapsing them would let an offline
    run report every module as opted out, and a caller deciding whether to fail has to
    be able to tell the difference.

    Never raises. stdlib only, because CI installs no Python dependencies for this.
    """
    import urllib.error
    import urllib.request
    req = urllib.request.Request(url, headers={
        "Accept": "application/json",
        "User-Agent": "DT_PSA_OPCV-compatibility-check",
    })
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            raw = r.read()
        return {"status": "ok", "data": json.loads(raw.decode("utf-8")),
                "raw": raw, "detail": None}
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return {"status": "missing", "data": None, "raw": None, "detail": "404"}
        return {"status": "unreachable", "data": None, "raw": None,
                "detail": f"HTTP {e.code}"}
    except json.JSONDecodeError as e:
        return {"status": "unreachable", "data": None, "raw": None,
                "detail": f"not valid JSON: {e}"}
    except Exception as e:                      # URLError, timeout, TLS, DNS
        return {"status": "unreachable", "data": None, "raw": None,
                "detail": f"{type(e).__name__}: {e}"}
